=== MG-Automation-Technologies/dms/trunk/openkm/src/main/resources/dtd/property-groups-1.1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT property-groups (property-group+)>

<!ELEMENT property-group (input|checkbox|textarea|select)*>
<!ATTLIST property-group
	label CDATA #REQUIRED
	name CDATA #REQUIRED
>

<!ELEMENT input (validator*)>
<!ATTLIST input
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT checkbox (validator*)>
<!ATTLIST checkbox
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT textarea (validator*)>
<!ATTLIST textarea 
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT select (option+, validator*)>
<!ATTLIST select
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	type (simple|multiple) "simple"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT option EMPTY>
<!ATTLIST option
	label CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT validator EMPTY>
<!ATTLIST validator
	type CDATA #REQUIRED
	parameter CDATA #IMPLIED
>

=== MG-Automation-Technologies/dms/trunk/openkm/src/test/resources/templates/PropertyGroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE property-groups PUBLIC "-//OpenKM//DTD Property Groups 1.0//EN"
                                 "http://www.openkm.com/dtd/property-groups-1.1.dtd">
<property-groups>
  <property-group label="Sample Form" name="okg:form">
    <input label="Name" name="okp:form.name"/>
    <input label="Bird Date" name="okp:form.bird_date" type="date" />
    <select label="Language" name="okp:form.language" type="simple">
      <option label="Java" value="java"/>
      <option label="Python" value="python"/>
      <option label="PHP" value="php" />
    </select>
  </property-group>
</property-groups>
