=== MG-Automation-Technologies/dms/trunk/openkm/src/main/resources/dtd/workflow-forms-1.1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT workflow-forms (workflow-form+)>

<!ELEMENT workflow-form (input|checkbox|textarea|select|button)*>
<!ATTLIST workflow-form
	task CDATA #REQUIRED
>

<!ELEMENT input (validator*)>
<!ATTLIST input
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	type CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT checkbox (validator*)>
<!ATTLIST checkbox
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	value (true|false) "false"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT textarea (validator*)>
<!ATTLIST textarea 
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT select (option+, validator*)>
<!ATTLIST select
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	type (simple|multiple) "simple"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ELEMENT option EMPTY>
<!ATTLIST option
	label CDATA #REQUIRED
	value CDATA #REQUIRED
	selected (true|false) "false"
>

<!ELEMENT validator EMPTY>
<!ATTLIST validator
	type CDATA #REQUIRED
	parameter CDATA #IMPLIED
>

<!ELEMENT button EMPTY>
<!ATTLIST button
	label CDATA #REQUIRED
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	type (submit|transition) "submit"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

=== MG-Automation-Technologies/dms/tags/5.1/openkm/src/test/resources/forms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE workflow-forms PUBLIC "-//OpenKM//DTD Workflow Forms 1.1//EN"
                                "http://www.openkm.com/dtd/workflow-forms-1.1.dtd">
<workflow-forms>
  <workflow-form task="start">
  	<input label="Quantity" name="quantity" value="10"/>
  	<button name="save" label="Save" />
  </workflow-form>
  <workflow-form task="user_info">
    <input label="Name" type="text" name="name" value="John" />
    <input label="Surname" type="text" name="surname" value="Doe" />
    <textarea label="Info" name="info" value=""/>
    <select label="Type" name="type" type="simple">
      <option label="Type 1" value="t1" />
      <option label="Type 2" value="t2" selected="true" />
      <option label="Type 3" value="t3" />
    </select>
    <button name="goto_1" label="Goto 1" value="route 1" type="transition" />
    <button name="goto_2" label="Goto 2" value="route 2" type="transition" />
  </workflow-form>
</workflow-forms>
